spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/istory} # ì˜ˆdbc:mysql://localhost:3306/istory
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: USER-SERVICE
  jwt:
    issuer: user@gmail.com
    secret_key: study-springboot
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop # create | create-drop | update | validate | none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:postgresql://192.168.0.2:5433/postgres
#    username: postgres
#    password: admin123
#jwt:
#  issuer: dangtong@gmail.com
#  secret_key: study-springboot

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop # create | create-drop | update | validate | none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
##  h2:
##    console:
##      enabled: false
#  jwt:
#    issuer: dangtong@gmail.com
#    secret_key: study-springboot
